//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voodle.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileDevice
    {
        public MobileDevice()
        {
            this.PushNotifications = new HashSet<PushNotification>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public string SmartphonePlatform { get; set; }
        public string PushNotificationsRegistrationID { get; set; }
        public string DeviceID { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<PushNotification> PushNotifications { get; set; }
    }
}
